[package]
name = "catfood"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = "0.7.5"
clap = { version = "4.5.9", features = ["derive"] }
diesel = { version = "2.2.2", features = ["sqlite"] }
env_logger = "0.11.3"
log = "0.4.22"
tokio = { version = "1.38.1", features = ["full"] }
